version: '3.1'

services:
  app:
    build: .
    command: bash -c "python /project/manage.py collectstatic -v0 --noinput && python /project/manage.py migrate --noinput && cd /project && gunicorn least.wsgi --bind=0.0.0.0:8000 --workers=3"
    stdin_open: true
    tty: true
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
    volumes:
      - ./project:/project
      - ./static:/static

  nginx:
    image: "nginx"
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/prod/config/app.conf/:/etc/nginx/conf.d/
      - ./nginx/prod/examinationsystem_me:/ssl/
    ports:
      - 80:80
      - 443:433